baseURL: https://dhar01.github.io/
languageCode: en-us
title: Loknath's Space
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

enableRobotsTXT: true

#services:
  #googleAnalytics:
    #id: G-MEASUREMENT_ID
  #disqus:
    #shortname: your-disqus-shortname

pagination:
  pagerSize: 3

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    #- identifier: gallery
    #  name: Gallery
    #  title: Blog posts
    #  url: /gallery
    #  weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Loknath's Space"
  description: Loknath's portfolio and blog
  # staticPath: ""  # The path to serve the static files from
  favicon: "/favicon.ico"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    defaultTheme: "dark" # light

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # When using hex codes for colors, quotations must be used along with the # sign
  # color:
  #   textColor: "#343a40"
  #   secondaryTextColor: "#6c757d"
  #   textLinkColor: "#007bff"
  #   backgroundColor: "#eaedf0"
  #   secondaryBackgroundColor: "#64ffda1a"
  #   primaryColor: "#007bff"
  #   secondaryColor: "#f8f9fa"

  #   darkmode:
  #     textColor: "#e4e6eb"
  #     secondaryTextColor: "#b0b3b8"
  #     textLinkColor: "#ffffff"
  #     backgroundColor: "#18191a"
  #     secondaryBackgroundColor: "#212529"
  #     primaryColor: "#ffffff"
  #     secondaryColor: "#212529"

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "loki" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    enableSeparator: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Loknath Dhar"
    subtitle: "Jr. Software Engineer"
    content: "A Golang and Linux enthusiast. I write code for both - humans and machines."
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "https://drive.google.com/file/d/1GLx_3ww5SVQ3NA6Vpq3gPYFW2yrWT4Tc/view"
      download: true
      newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/Dhar01
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/dhar01/
        - icon: fab fa-telegram
          url: https://t.me/Dhar01

  # About
  about:
    enable: true
    title: "About Me"
    image: "/loki.jpg"
    content: |-
      I'm a backend-focused Software Engineer, passionate about Linux, automation, and building efficient command-line tools. I enjoy working on projects that dive into system administration, and backend development, and constantly exploring new ways to make processes faster, simpler, and more secure!

      I am currently working on a project "MediTrust", an backend solution for online pharmacy.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Go"
        - "Python"
        - "PostgreSQL"
        - "Docker"
        - "Linux"
        - "Restful APIs"
        - "Git"
        - "JavaScript"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Jr. DevOps Engineer"
        company: "jobdesk"
        companyUrl: "https://www.jobdesk.com/"
        date: "July 2022 - May 2023"
        content: "Focused on administration of Apache Solr database, monitoring with zabbix, maintenance of cloud & Datafarm services, and documentations."

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Bachelor of Science in Computer Science"
        school:
          name: "Daffodil International University"
          url: "https://daffodilvarsity.edu.bd/"
        date: "2017 - 2022"
        GPA: "3.09 out of 4.0"
      - title: "Higher Secondary Certificate (HSC)"
        school:
          name: "Dr. Mahbubur Rahman Molla College (DMRC)"
          url: "https://dmrc.edu.bd/"
        date: "2013-2015"
        GPA: "5.0 out of 5.0"
      - title: "Secondary School Certificate (SSC)"
        school:
          name: "Pagla High School"
          url: "https://locator.eduportalbd.com/institutes/?ins=112440"
        date: "2009-2013"
        GPA: "5.0 out of 5.0"

  # Achievements
  achievements:
    enable: false
    # title: "Custom Name"
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
        image: /images/achievement.jpg
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
        image: /images/achievement.jpg
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
        image: /images/achievement.jpg
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: MediTrust
        content: Fast and reliable backend system for an online pharmacy, powered by Go and PostgreSQL.
        image: /meditrust.png
        badges:
          - "Go"
          - "PostgreSQL"
          - "sqlc"
        links:
          - icon: fab fa-github
            url: https://github.com/Dhar01/MediTrust

      - title: Static Site Generator
        content: A static site generator written in Python
        image: /staticsite.png
        featured:
          name: Demo
          link: https://dhar01.github.io/static_site/
        badges:
          - "Python"
          - "HTML"
          - "Markdown"
        links:
          - icon: fab fa-github
            url: https://github.com/Dhar01/static_site

      - title: Gator
        content: A RSS feed aggregator for command line.
        image: /gator.png
        badges:
          - "Go"
          - "PostgreSQL"
          - "sqlc"
        links:
          - icon: fab fa-github
            url: https://github.com/Dhar01/Gator

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: For any kind of query-
    btnName: Mail me
    btnLink: mailto:loknathdhar66@gmail.com
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"
    #   messageRows: 5

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/Dhar01
      linkedin: https://www.linkedin.com/in/dhar01/
      facebook: https://facebook.com/Dhar01

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    socialShare: true
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>